// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrFrafz2vNu03HvMn9WcXwDh4mGUyKRXI',
    appId: '1:782659788938:web:757e1f47d79067913e4d73',
    messagingSenderId: '782659788938',
    projectId: 'ismail-a21c4',
    authDomain: 'ismail-a21c4.firebaseapp.com',
    storageBucket: 'ismail-a21c4.appspot.com',
    measurementId: 'G-0GNKNWKYWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW1XE9WcRw9MV28ezT-UX-oKqSWqLvTsM',
    appId: '1:782659788938:android:0d04f3c4b67d21f93e4d73',
    messagingSenderId: '782659788938',
    projectId: 'ismail-a21c4',
    storageBucket: 'ismail-a21c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2dyO5wazjlmhLgqREVy6GtVutBfnlv-E',
    appId: '1:782659788938:ios:0d7df385807c66b23e4d73',
    messagingSenderId: '782659788938',
    projectId: 'ismail-a21c4',
    storageBucket: 'ismail-a21c4.appspot.com',
    iosBundleId: 'com.example.untitled23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2dyO5wazjlmhLgqREVy6GtVutBfnlv-E',
    appId: '1:782659788938:ios:e45e281e2e7f94a13e4d73',
    messagingSenderId: '782659788938',
    projectId: 'ismail-a21c4',
    storageBucket: 'ismail-a21c4.appspot.com',
    iosBundleId: 'com.example.untitled23.RunnerTests',
  );
}
